spring:
    profiles:
        active: local
        include:
            - aws
            - aws-credential
            - ACCOUNT
    datasource:
        hikari:
            pool-name: tilbox-pool
            minimum-idle: 5
            maximum-pool-size: 50
            connection-timeout: 3000
            idle-timeout: 600000
            max-lifetime: 1800000
            transaction-isolation: TRANSACTION_READ_COMMITTED
        url: jdbc:h2:mem:tilbox;DB_CLOSE_ON_EXIT=FALSE
        username: tilbox
        password: retrospective6
    jpa:
        generate-ddl: true
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                show_sql: true
                use_sql_comments: true
    flyway:
        enabled: false
    h2:
        console:
            enabled: true
            path: /h2-console
    mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                mime:
                    charset: UTF-8

springfox:
    documentation:
        swagger-ui:
            base-url: /documentation

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
