name: "Chromatic Deployment"

on:
  pull_request:
    paths:
      - client/**
    branches:
      - '**'
  push:
    paths:
      - client/**
    branches:
      - main


jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Environment Variables File for Production
        run: |
          echo "API_HOSTNAME=$API_HOSTNAME" >> .env
          echo "API_PORT=$API_PORT" >> .env
          echo "API_VERSION=$API_VERSION" >> .env
          echo "API_HOST=$API_HOST" >> .env
        env:
          API_HOSTNAME: ${{ secrets.API_HOSTNAME }}
          API_PORT: ${{ secrets.API_PORT }}
          API_VERSION: ${{ secrets.API_VERSION }}
          API_HOST: ${{ secrets.API_HOST }}

      - name: Install dependencies
        run: |
          echo 'nodeLinker: "node-modules"' >> .yarnrc.yml
          yarn rebuild
          yarn build

      - name: Init msw
        run: |
          yarn msw init public/ -save

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          workingDir: client
