name: "Chromatic Deployment"

on:
  pull_request:
    paths:
      - client/**
    branches:
      - '**'
  push:
    paths:
      - client/**
    branches:
      - main


jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          echo 'nodeLinker: "node-modules"' >> .yarnrc.yml
          yarn rebuild
          yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: client